# Generated by Django 4.2.30 on 2026-04-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='image',
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(blank=True, help_text='e.g., 500mg', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='e.g., 7 days', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(blank=True, help_text='e.g., 2 times a day', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='prescription_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
