# Generated by Django 4.2.30 on 2026-04-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_prescription_image_prescription_dosage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_risk_limit', models.PositiveIntegerField(default=15)),
                ('moderate_risk_limit', models.PositiveIntegerField(default=30)),
                ('high_risk_limit', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
