# Generated by Django 4.2.30 on 2026-04-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.PositiveIntegerField(blank=True, help_text='Amount in mg', null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Total days', null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, help_text='Times per day', null=True),
        ),
    ]
